### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
_Remember to use `[ci-skip]` on the merge commit message to avoid spamming Jenkins_ ✨ ♻️

Needs https://github.com/plone/plone.memoize/pull/34 merged and released in order to get the tests to pass here 😅 

That's what happens if dependencies are not declared properly 🍀

### CODE REVIEW

**Comment by gforcada** [comment]
@mauritsvanrees I made a release of `plone.memoize = 3.0.2` and updated `versions.cfg` on `buildout.coredev` for branches `6.0` and `6.1`.

That's not enough to get the tests to pass here, as the `constraints.txt` file being used https://dist.plone.org/release/6.0-dev/constraints.txt is not magically updated 😅 

Could that be something that can be automated? 🤔 either at GHA, plone.releaser, jenkins or mr.roboto level? Pick your preferred one 😄

**Comment by mauritsvanrees** [comment]
Well, if anything automatically updates `6.0-dev`, then that would currently ruin the 6.0.6rc1 pending release. :-/
I can update the file tomorrow after the final release.

**Comment by gforcada** [comment]
Indeed, we could have a specific `constraints.txt` that is automatically updated at any release being done (i.e. monitoring `versions.cfg` from `buildout.coredev`) that we can use for `plone/meta` CI stuff (maybe eventually Jenkins as well? 🤔 ) and then the specific ones that you use for the release process?

We had the idea to make `(requirements|constraints).txt` to be _leading_ and `versions.cfg` to be the mirror, whenever we get to that point, then as soon as we make a release with `plone.releaser` we will automatically have that 🎉

**Comment by mauritsvanrees** [comment]
The needed `plone.memoize = 3.0.2` has been on dist.plone.org/release/6.0-dev for a long time already, and I have updated the files today for good measure.
I merged master in here and made minor changes.  All fine locally now.

**Review by mauritsvanrees — APPROVED** [review]
@gforcada Can you check again yourself as well?
Can be merged when green.

**Comment by mauritsvanrees** [comment]
Only internal changes, so no Jenkins jobs needed, I would say.

**Comment by gforcada** [comment]
@mauritsvanrees Looks good, thanks! 😄

**Pull request merged**
